### ISSUE TITLE
brew installation failed, seems it automatically adds a `homebrew-` prefix

### ISSUE THREAD

**Issue by Jeff-Tian** [LEGO/assume-aws-sso-role#16]
```
➜  tools brew install LEGO/assume-aws-sso-role/assume-aws-sso-role
==> Tapping lego/assume-aws-sso-role
Cloning into '/opt/homebrew/Library/Taps/lego/homebrew-assume-aws-sso-role'...
remote: Repository not found.
fatal: repository 'https://github.com/lego/homebrew-assume-aws-sso-role/' not found
Error: Failure while executing; `git clone https://github.com/lego/homebrew-assume-aws-sso-role /opt/homebrew/Library/Taps/lego/homebrew-assume-aws-sso-role --origin=origin --template= --config core.fsmonitor=false` exited with 128.
```

Maybe we should rename this repo name to `homebrew-assume-aws-sso-role` ?

**Comment by LarsPede** [comment]
any workaround for this?

**Comment by relausen-tlg** [comment]
IMHO there are two correct (for some definition of "correct" 😄) ways of handling the naming convention stuff: Either update the README to describe @LarsPede's solution (which is not a workaround, but the exact way to use repos with non-brew-compliant naming) or create a separate repo with the `homebrew-` name prefix, only containing the Homebrew stuff (e.g. the formula), thus enabling the short form of `install` et al.

The latter seems to be a popular way of structurizing taps. I like that approach, since it keeps the "actual" project separate from the Homebrew specific stuff. It might require the release job in CI/CD to compress the shell script file, at least as far as I have seen in the examples, but I'm not sure. If it is required then it should not be a showstopper 😄.

**Comment by relausen-tlg** [comment]
And now I noticed that I forgot to look into a PR that @jhd-lego created a long time ago with the change to the README that I just suggested 😄.

**Comment by relausen-tlg** [comment]
Closed this issue since the "new" way to install via Homebrew is now described in the README.
